Code/ASM/Controllers/TrainerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASM.Models;

namespace ASM.Controllers
{
    public class TrainerController : Controller
    {
        // GET: Trainer
        public ActionResult ProfileTrainer()
        {
            Training_managementEntities db = new Training_managementEntities();
            List<Profile_User> pro = db.Profile_User.ToList();
            return View();

        }

    }
}

Code/ASM/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/Website/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Website/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="~/Website/css/fullcalendar.css" />
    <link rel="stylesheet" href="~/Website/css/matrix-style.css" />
    <link rel="stylesheet" href="~/Website/css/matrix-media.css" />
    <link href="~/Website/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Website/css/jquery.gritter.css" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
</head>
<body>

    @if (Session["position"].ToString() != "admin")
    {
        <script>
            window.location.href = "/Home/Login";
        </script>
    }
        <!--Header-part-->
        <div id="header">
            <h1><a href="~/Website/img/logo.png">Admin</a></h1>
        </div>
        <!--close-Header-part-->
        <!--top-Header-menu-->
        <div id="user-nav" class="navbar navbar-inverse">
            <ul class="nav">
                <li class="dropdown" id="profile-messages">
                    <a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle">
                        <i class="icon icon-user"></i>  <span class="text">
                            @if (Session["username"] != null)
                            {
                                <text>
                                    Welcome @Session["username"].ToString()
                                </text>
                            }
                        </span><b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#"><i class="icon-user"></i> My Profile</a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="icon-check"></i> My Tasks</a></li>
                        <li class="divider"></li>
                        <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                    </ul>
                </li>
                <li class=""><a title="" href="/Home/Logout/"><i class="icon icon-share-alt"></i> <span class="text">Logout</span></a></li>
            </ul>
        </div>
        <!--close-top-Header-menu-->
        <!--start-top-serch-->
        <div id="search">
            <input type="text" placeholder="Search here..." />
            <button type="submit" class="tip-bottom" title="Search"><i class="icon-search icon-white"></i></button>
        </div>
        <!--close-top-serch-->
        <!--sidebar-menu-->
        <div id="sidebar">
            <a href="#" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a>
            <ul>
                <li>@Html.ActionLink("Dashboard", "Userhome", "Home")</li>
                <li>@Html.ActionLink("Acount Management", "Staff", "Admin")</li>
            </ul>
        </div>
        <!--sidebar-menu-->
        <!--main-container-part-->
        <div id="content">
            <!--breadcrumbs-->
            @RenderBody()
            <!--End-breadcrumbs-->
        </div>
        <!--end-main-container-part-->
        <!--Footer-part-->
        <div class="row-fluid">
            <div id="footer" class="span12"> 2013 &copy; Matrix Admin. Brought to you by <a href="http://themedesigner.in">Themedesigner.in</a> </div>
        </div>
        <!--end-Footer-part-->
        <script src="~/Website/js/excanvas.min.js"></script>
        <script src="~/Website/js/jquery.min.js"></script>
        <script src="~/Website/js/jquery.ui.custom.js"></script>
        <script src="~/Website/js/bootstrap.min.js"></script>
        <script src="~/Website/js/jquery.flot.min.js"></script>
        <script src="~/Website/js/jquery.flot.resize.min.js"></script>
        <script src="~/Website/js/jquery.peity.min.js"></script>
        <script src="~/Website/js/fullcalendar.min.js"></script>
        <script src="~/Website/js/matrix.js"></script>
        <script src="~/Website/js/matrix.dashboard.js"></script>
        <script src="~/Website/js/jquery.gritter.min.js"></script>
        <script src="~/Website/js/matrix.interface.js"></script>
        <script src="~/Website/js/matrix.chat.js"></script>
        <script src="~/Website/js/jquery.validate.js"></script>
        <script src="~/Website/js/matrix.form_validation.js"></script>
        <script src="~/Website/js/jquery.wizard.js"></script>
        <script src="~/Website/js/jquery.uniform.js"></script>
        <script src="~/Website/js/select2.min.js"></script>
        <script src="~/Website/js/matrix.popover.js"></script>
        <script src="~/Website/js/jquery.dataTables.min.js"></script>
        <script src="~/Website/js/matrix.tables.js"></script>
        <script type="text/javascript">
            // This function is called from the pop-up menus to transfer to
            // a different page. Ignore if the value returned is a null string:
            function goPage(newURL) {

                // if url is empty, skip the menu dividers and reset the menu selection to default
                if (newURL != "") {

                    // if url is "-", it is this page -- reset the menu:
                    if (newURL == "-") {
                        resetMenu();
                    }
                    // else, send page to designated URL
                    else {
                        document.location.href = newURL;
                    }
                }
            }

            // resets the menu selection upon entry to this page:
            function resetMenu() {
                document.gomenu.selector.selectedIndex = 2;
            }
        </script>
    </body>
</html>

Code/ASM/Views/Shared/_LayoutPage2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/Website/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Website/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="~/Website/css/uniform.css" />
    <link rel="stylesheet" href="~/Website/css/select2.css" />
    <link rel="stylesheet" href="~/Website/css/matrix-style.css" />
    <link rel="stylesheet" href="~/Website/css/matrix-media.css" />
    <link href="~/Website/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
</head>
<body>

    @if (Session["position"].ToString() != "staff")
    {
        <script>
            window.location.href = "/Home/Login";
        </script>
    }
    <!--Header-part-->
    <div id="header">
        <h1><a href="~/Website/img/logo.png">Admin</a></h1>
    </div>
    <!--close-Header-part-->
    <!--top-Header-menu-->
    <div id="user-nav" class="navbar navbar-inverse">
        <ul class="nav">
            <li class="dropdown" id="profile-messages">
                <a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle">
                    <i class="icon icon-user"></i>  <span class="text">
                        @if (Session["username"] != null)
                        {
                            <text>
                                Welcome @Session["username"].ToString()
                            </text>
                        }
                    </span><b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#"><i class="icon-user"></i> My Profile</a></li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="icon-check"></i> My Tasks</a></li>
                    <li class="divider"></li>
                    <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                </ul>
            </li>

            <li class=""><a title="" href="/Home/Logout/"><i class="icon icon-share-alt"></i> <span class="text">Logout</span></a></li>
        </ul>
    </div>
    <!--start-top-serch-->
    <div id="search">
        <input type="text" placeholder="Search here..." />
        <button type="submit" class="tip-bottom" title="Search"><i class="icon-search icon-white"></i></button>
    </div>
    <!--close-top-serch-->
    <!--sidebar-menu-->
    <div id="sidebar">
        <a href="#" class="visible-phone"><i class="icon icon-th"></i>Table</a>
        <ul>
            <li>@Html.ActionLink("Trainee Account", "TraineeAccount", "StaffPage")</li>
            <li>@Html.ActionLink("Profile", "ProTrainer", "StaffPage")</li>
            <li class="submenu">
                <a href="#"><i class="icon icon-th-list"></i> <span>Course/Topic</span> <span class="label label-important">3</span></a>
                <ul>
                    <li>@Html.ActionLink("Category", "StaffMana", "StaffPage")</li>
                    <li>@Html.ActionLink("Course", "CourseMana", "StaffPage")</li>
                    <li>@Html.ActionLink("Topic", "TopicMana", "StaffPage")</li>
                </ul>
            </li>
        </ul>
    </div>
    <div id="content">
        @RenderBody()
    </div>
    <!--Footer-part-->
    <div class="row-fluid">
        <div id="footer" class="span12"> 2013 &copy; Matrix Admin. Brought to you by <a href="http://themedesigner.in">Themedesigner.in</a> </div>
    </div>
    <!--end-Footer-part-->
    <script src="~/Website/js/jquery.min.js"></script>
    <script src="~/Website/js/jquery.ui.custom.js"></script>
    <script src="~/Website/js/bootstrap.min.js"></script>
    <script src="~/Website/js/jquery.uniform.js"></script>
    <script src="~/Website/js/select2.min.js"></script>
    <script src="~/Website/js/jquery.dataTables.min.js"></script>
    <script src="~/Website/js/matrix.js"></script>
    <script src="~/Website/js/matrix.tables.js"></script>
</body>
</html>

Code/ASM/Views/Shared/_LayoutPage3.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/Website/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Website/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="~/Website/css/uniform.css" />
    <link rel="stylesheet" href="~/Website/css/select2.css" />
    <link rel="stylesheet" href="~/Website/css/matrix-style.css" />
    <link rel="stylesheet" href="~/Website/css/matrix-media.css" />
    <link href="~/Website/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
</head>
<body>

    @if (Session["position"].ToString() != "trainer" & (Session["position"].ToString() != "trainee"))
    {
        <script>
            window.location.href = "/Home/Login";
        </script>
    }
    <!--Header-part-->
    <div id="header">
        <h1><a href="dashboard.html">Matrix Admin</a></h1>
    </div>
    <!--close-Header-part-->
    <!--top-Header-menu-->
    <div id="user-nav" class="navbar navbar-inverse">
        <ul class="nav">
            <li class="dropdown" id="profile-messages">
                <a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle">
                    <i class="icon icon-user"></i>  <span class="text">
                        @if (Session["username"] != null)
                        {
                            <text>
                                Welcome @Session["username"].ToString()
                            </text>
                        }
                    </span><b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#"><i class="icon-user"></i> My Profile</a></li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="icon-check"></i> My Tasks</a></li>
                    <li class="divider"></li>
                    <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                </ul>
            </li>

            <li class=""><a title="" href="/Home/Logout/"><i class="icon icon-share-alt"></i> <span class="text">Logout</span></a></li>
        </ul>
    </div>
    <!--start-top-serch-->
    <div id="search">
        <input type="text" placeholder="Search here..." />
        <button type="submit" class="tip-bottom" title="Search"><i class="icon-search icon-white"></i></button>
    </div>
    <!--close-top-serch-->
    <!--sidebar-menu-->
    <div id="sidebar">
        <a href="#" class="visible-phone"><i class="icon icon-th"></i>Table</a>
        <ul>
            <li>@Html.ActionLink("Profile", "ProfileTrainer", "Trainer")</li>
            <li>@Html.ActionLink("Course/Topic", "Management", "Trainer")</li>
        </ul>
    </div>
    <div id="content">
        @RenderBody()
    </div>
    <!--Footer-part-->
    <div class="row-fluid">
        <div id="footer" class="span12"> 2013 &copy; Matrix Admin. Brought to you by <a href="http://themedesigner.in">Themedesigner.in</a> </div>
    </div>
    <!--end-Footer-part-->
    <script src="~/Website/js/jquery.min.js"></script>
    <script src="~/Website/js/jquery.ui.custom.js"></script>
    <script src="~/Website/js/bootstrap.min.js"></script>
    <script src="~/Website/js/jquery.uniform.js"></script>
    <script src="~/Website/js/select2.min.js"></script>
    <script src="~/Website/js/jquery.dataTables.min.js"></script>
    <script src="~/Website/js/matrix.js"></script>
    <script src="~/Website/js/matrix.tables.js"></script>
</body>
</html>